# Generated by Django 2.2.6 on 2019-10-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsercomments',
            name='video',
        ),
    ]
