# Generated by Django 2.2.6 on 2019-10-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_parservideoid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parservideoid',
            options={'verbose_name': 'Данные видео', 'verbose_name_plural': 'Данные видео'},
        ),
        migrations.AddField(
            model_name='parsercomments',
            name='video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.ParserVideoId', verbose_name='Данные видео'),
            preserve_default=False,
        ),
    ]
