# Generated by Django 2.2.6 on 2019-10-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191024_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='parservideoid',
            name='video_id',
            field=models.CharField(default='', max_length=125, verbose_name='Видео id'),
            preserve_default=False,
        ),
    ]
