# Generated by Django 2.2.6 on 2019-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_parservideoid_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parservideoid',
            name='name_video',
            field=models.CharField(default='', max_length=255, verbose_name='Название видео'),
            preserve_default=False,
        ),
    ]
